print("Welcome to William Academy")
print("We will like to know more about so kindly fill out the following")
name = input("What is your name:")
surname = input("What is your surname: ")
age = input("How old are you: ")
gender = input("Sex: ")
programming_status = input("How many years have experience do you have in programming: ")
print("Hi " + name + " " + surname + "." + " Welcome once again to William Academy. ")
print("You have stated you are " + age + " years old and have " + programming_status + " years experience in programming. ")
print("We will do our best to find a suitable course level for you and get back to you ASAP.")